# Generated by Django 4.0.6 on 2022-07-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Familia', '0002_alter_familia_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
