# Generated by Django 4.0.6 on 2022-07-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Familia', '0003_alter_familia_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia',
            name='creation_date',
        ),
        migrations.AlterField(
            model_name='familia',
            name='birthday_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
